In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from pathlib import Path

PROJECT_NAME = "Sanskrit_Phi4_Finetuning"

BASE_DIR = Path("/content/drive/MyDrive") / PROJECT_NAME

folders = [
    "dataset",
    "evaluation",
    "outputs",
    "models",
    "logs",
    "notebooks",
]

for folder in folders:
    (BASE_DIR / folder).mkdir(parents=True, exist_ok=True)

print("=" * 60)
print("Project directory created successfully!")
print("=" * 60)

for folder in folders:
    print(BASE_DIR / folder)

============================================================
Project directory created successfully!
============================================================
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/dataset
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/evaluation
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/models
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/logs
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/notebooks

In [ ]:


import sys
import platform
import torch

print("=" * 60)
print("Python Version :", sys.version)
print("Platform       :", platform.platform())
print("PyTorch Version:", torch.__version__)
print("CUDA Available :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU Name       :", torch.cuda.get_device_name(0))
    print("CUDA Version   :", torch.version.cuda)
else:
    print("GPU Name       : No GPU Detected")

print("=" * 60)

============================================================
Python Version : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Platform       : Linux-6.6.122+-x86_64-with-glibc2.35
PyTorch Version: 2.11.0+cu128
CUDA Available : True
GPU Name       : Tesla T4
CUDA Version   : 12.8
============================================================

In [ ]:


# Install Unsloth and required packages
!pip -q install --upgrade pip

!pip -q install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

!pip -q install \
transformers \
datasets \
trl \
accelerate \
peft \
bitsandbytes \
sentencepiece \
evaluate \
sentence-transformers \
skrutable \
indic-transliteration \
tensorboard \
pandas \
numpy \
matplotlib \
scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Building wheel for unsloth (pyproject.toml) ... done

In [ ]:


import torch

print("=" * 60)
print("PyTorch Version :", torch.__version__)
print("CUDA Available  :", torch.cuda.is_available())

try:
    import unsloth
    print("\n✅ Unsloth Imported Successfully")
    print("Version :", getattr(unsloth, "__version__", "Unknown"))
except Exception as e:
    print("\n❌ Unsloth Import Failed")
    print(e)

print("=" * 60)

============================================================
PyTorch Version : 2.11.0+cu128
CUDA Available  : True
🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

Accessing `is_flash_linear_attention_available` from `.models.aria.image_processing_aria`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.aria.image_processing_pil_aria`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.auto.image_processing_auto`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.beit.image_processing_beit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.beit.image_processing_pil_beit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bit.image_processing_bit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bit.image_processing_pil_bit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.blip.image_processing_blip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.blip.image_processing_pil_blip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bridgetower.image_processing_bridgetower`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.bridgetower.image_processing_pil_bridgetower`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chameleon.image_processing_chameleon`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chameleon.image_processing_pil_chameleon`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chinese_clip.image_processing_chinese_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chinese_clip.image_processing_chinese_pil_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.chmv2.image_processing_chmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.clip.image_processing_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.clip.image_processing_pil_clip`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.cohere2_vision.image_processing_cohere2_vision`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.conditional_detr.image_processing_conditional_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.conditional_detr.image_processing_pil_conditional_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.convnext.image_processing_convnext`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.convnext.image_processing_pil_convnext`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl.image_processing_deepseek_vl`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl.image_processing_pil_deepseek_vl`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl_hybrid.image_processing_deepseek_vl_hybrid`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deepseek_vl_hybrid.image_processing_pil_deepseek_vl_hybrid`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deformable_detr.image_processing_deformable_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deformable_detr.image_processing_pil_deformable_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deit.image_processing_deit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.deit.image_processing_pil_deit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.depth_pro.image_processing_depth_pro`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.detr.image_processing_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.detr.image_processing_pil_detr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dinov3_vit.image_processing_dinov3_vit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.donut.image_processing_donut`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.donut.image_processing_pil_donut`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dpt.image_processing_dpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.dpt.image_processing_pil_dpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientloftr.image_processing_efficientloftr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientloftr.image_processing_pil_efficientloftr`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientnet.image_processing_efficientnet`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.efficientnet.image_processing_pil_efficientnet`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.emu3.image_processing_emu3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.eomt.image_processing_eomt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.eomt.image_processing_pil_eomt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.ernie4_5_vl_moe.image_processing_ernie4_5_vl_moe`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.ernie4_5_vl_moe.image_processing_pil_ernie4_5_vl_moe`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.flava.image_processing_flava`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.flava.image_processing_pil_flava`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.fuyu.image_processing_fuyu`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.fuyu.image_processing_pil_fuyu`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma3.image_processing_gemma3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma3.image_processing_pil_gemma3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma4.image_processing_gemma4`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.gemma4.image_processing_pil_gemma4`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm46v.image_processing_glm46v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm46v.image_processing_pil_glm46v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm4v.image_processing_glm4v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm4v.image_processing_pil_glm4v`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm_image.image_processing_glm_image`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glm_image.image_processing_pil_glm_image`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glpn.image_processing_glpn`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.glpn.image_processing_pil_glpn`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.got_ocr2.image_processing_got_ocr2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.got_ocr2.image_processing_pil_got_ocr2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.grounding_dino.image_processing_grounding_dino`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.grounding_dino.image_processing_pil_grounding_dino`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics.image_processing_idefics`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics.image_processing_pil_idefics`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics2.image_processing_idefics2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics2.image_processing_pil_idefics2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics3.image_processing_idefics3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.idefics3.image_processing_pil_idefics3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.imagegpt.image_processing_imagegpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.imagegpt.image_processing_pil_imagegpt`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.janus.image_processing_janus`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.janus.image_processing_pil_janus`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.kosmos2_5.image_processing_kosmos2_5`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.kosmos2_5.image_processing_pil_kosmos2_5`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv2.image_processing_layoutlmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv2.image_processing_pil_layoutlmv2`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv3.image_processing_layoutlmv3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.layoutlmv3.image_processing_pil_layoutlmv3`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.
Accessing `is_flash_linear_attention_available` from `.models.levit.image_processing_levit`. Returning `is_flash_linear_attention_available` instead. Behavior may be different and this alias will be removed in future versions.

🦥 Unsloth Zoo will now patch everything to make training faster!

✅ Unsloth Imported Successfully
Version : 2026.7.2
============================================================

In [ ]:


from pathlib import Path

PROJECT_NAME = "Sanskrit_Phi4_Finetuning"

BASE_DIR = Path("/content/drive/MyDrive") / PROJECT_NAME

DATASET_DIR   = BASE_DIR / "dataset"
EVAL_DIR      = BASE_DIR / "evaluation"
OUTPUT_DIR    = BASE_DIR / "outputs"
MODEL_DIR     = BASE_DIR / "models"
LOG_DIR       = BASE_DIR / "logs"
NOTEBOOK_DIR  = BASE_DIR / "notebooks"

for folder in [DATASET_DIR, EVAL_DIR, OUTPUT_DIR, MODEL_DIR, LOG_DIR, NOTEBOOK_DIR]:
    folder.mkdir(parents=True, exist_ok=True)

print("=" * 60)
print("Project Root :", BASE_DIR)
print("=" * 60)

print("Dataset   :", DATASET_DIR)
print("Evaluation:", EVAL_DIR)
print("Outputs   :", OUTPUT_DIR)
print("Models    :", MODEL_DIR)
print("Logs      :", LOG_DIR)
print("Notebook  :", NOTEBOOK_DIR)

print("=" * 60)

============================================================
Project Root : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning
============================================================
Dataset   : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/dataset
Evaluation: /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/evaluation
Outputs   : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs
Models    : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/models
Logs      : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/logs
Notebook  : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/notebooks
============================================================

In [ ]:
#UPLOADING FILES

from google.colab import files
import shutil
from pathlib import Path

print("=" * 60)
print("Upload the following files:")
print("1. dataset_full.csv")
print("2. evaluation.py")
print("3. utils.py")
print("4. ft_sanskrit.py")
print("=" * 60)

uploaded = files.upload()

for filename in uploaded.keys():

    src = Path(filename)

    if filename.endswith(".csv"):
        dst = DATASET_DIR / filename

    elif filename.endswith(".py"):
        dst = EVAL_DIR / filename

    else:
        continue

    shutil.move(str(src), str(dst))
    print(f"✅ Saved -> {dst}")

print("\nAll uploaded files have been copied to Google Drive successfully!")

============================================================
Upload the following files:
1. dataset_full.csv
2. evaluation.py
3. utils.py
4. ft_sanskrit.py
============================================================

Saving utils.py to utils.py
Saving ft_sanskrit.py to ft_sanskrit.py
Saving evaluation.py to evaluation.py
✅ Saved -> /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/evaluation/utils.py
✅ Saved -> /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/evaluation/ft_sanskrit.py
✅ Saved -> /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/evaluation/evaluation.py

All uploaded files have been copied to Google Drive successfully!

# TASK 1

In [ ]:
# LOAD DATASET
# -------------

import pandas as pd

DATASET_PATH = DATASET_DIR / "dataset_full.csv"

df = pd.read_csv(DATASET_PATH)

print("=" * 70)
print("Dataset Loaded Successfully!")
print("=" * 70)

print(f"Dataset Shape : {df.shape}")
print(f"Rows          : {len(df)}")
print(f"Columns       : {len(df.columns)}")

print("\nColumn Names:")
for i, col in enumerate(df.columns, 1):
    print(f"{i}. {col}")

print("=" * 70)

======================================================================
Dataset Loaded Successfully!
======================================================================
Dataset Shape : (32941, 4)
Rows          : 32941
Columns       : 4

Column Names:
1. sa
2. hi
3. meter
4. prompt
======================================================================

In [ ]:
# INSPECTING DATASET
# -------------------

print("=" * 70)
print("First 5 Rows")
print("=" * 70)

display(df.head())

print("\n" + "=" * 70)
print("Missing Values")
print("=" * 70)

display(df.isnull().sum())

print("\n" + "=" * 70)
print("Duplicate Rows")
print("=" * 70)

print(df.duplicated().sum())

print("\n" + "=" * 70)
print("Meter Distribution (Top 15)")
print("=" * 70)

display(df["meter"].value_counts().head(15))

======================================================================
First 5 Rows
======================================================================

,sa,hi,meter,prompt
0,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...
1,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...
2,स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन...,वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर च...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...
3,अहोरात्रेक्षणो दिव्यो वेदाड़ः श्रुतिभूषण: आज्य...,"दिन और रात्रि उनके नेत्र हैं, वे दिव्यस्वरूप ह...",anuṣṭubh,The goal is to generate Sanskrit verse that fo...
4,तथा हि दृड्डा बीभत्सुमुपायान्तं प्रशंसति यथा स...,तभी तो अर्जुन को आते देख ये उसकी प्रशंसा कर रह...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...

======================================================================
Missing Values
======================================================================

sa        0
hi        0
meter     0
prompt    0
dtype: int64

======================================================================
Duplicate Rows
======================================================================
63

======================================================================
Meter Distribution (Top 15)
======================================================================

meter
anuṣṭubh    32941
Name: count, dtype: int64

In [ ]:
# REMOVING DUPLICATE ROWS
# -------------------------

initial_rows = len(df)

df = df.drop_duplicates().reset_index(drop=True)

removed = initial_rows - len(df)

print("=" * 70)
print("Duplicate Removal Completed")
print("=" * 70)

print(f"Initial Rows   : {initial_rows}")
print(f"Removed Rows   : {removed}")
print(f"Remaining Rows : {len(df)}")

# Save checkpoint
checkpoint_path = OUTPUT_DIR / "01_dataset_without_duplicates.csv"
df.to_csv(checkpoint_path, index=False)

print("\n✅ Checkpoint saved to:")
print(checkpoint_path)

======================================================================
Duplicate Removal Completed
======================================================================
Initial Rows   : 32941
Removed Rows   : 63
Remaining Rows : 32878

✅ Checkpoint saved to:
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/01_dataset_without_duplicates.csv

In [ ]:
# Remove Verses Containing "उवाच"
# --------------------------------


initial_rows = len(df)

mask = df["sa"].str.contains("उवाच", na=False)

removed = mask.sum()

df = df[~mask].reset_index(drop=True)

print("=" * 70)
print("Removed Verses Containing 'उवाच'")
print("=" * 70)

print(f"Initial Rows   : {initial_rows}")
print(f"Removed Rows   : {removed}")
print(f"Remaining Rows : {len(df)}")

# Save checkpoint
checkpoint_path = OUTPUT_DIR / "02_dataset_without_uvacha.csv"
df.to_csv(checkpoint_path, index=False)

print("\n✅ Checkpoint saved to:")
print(checkpoint_path)

======================================================================
Removed Verses Containing 'उवाच'
======================================================================
Initial Rows   : 32878
Removed Rows   : 98
Remaining Rows : 32780

✅ Checkpoint saved to:
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/02_dataset_without_uvacha.csv

In [ ]:
# INITIALIZE SKRUTABLE METER VALIDATOR
# -------------------------------------------

from skrutable.meter_identification import MeterIdentifier


mi = MeterIdentifier()


sample_verse = df.loc[0, "sa"]

print("=" * 70)
print("Sample Sanskrit Verse")
print("=" * 70)
print(sample_verse)

print("\n" + "=" * 70)
print("Running Skrutable Meter Identification...")
print("=" * 70)

result = mi.identify_meter(
    sample_verse,
    from_scheme="DEV",
    resplit_option="resplit_max"
)

print("Meter Label:")
print(result.meter_label)

print("\nSyllable Pattern:")
print(result.syllable_weights)

print("\nTotal Syllables:")
print(len(result.syllable_weights.replace("\n", "")))

======================================================================
Sample Sanskrit Verse
======================================================================
न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्यार्थमुपयुञ्जीत धर्मं कामान् विसर्जयेत् ॥

======================================================================
Running Skrutable Meter Identification...
======================================================================
Meter Label:
anuṣṭubh (1,2: pathyā; 3,4: pathyā)

Syllable Pattern:
lggllggl
gggglglg
gglllggl
gggglglg

Total Syllables:
32

In [ ]:
# CHECK DUPLICATE COLUMNS

from collections import Counter

counts = Counter(df.columns)

duplicates = {k: v for k, v in counts.items() if v > 1}

print("Duplicate columns:")
print(duplicates)

Duplicate columns:
{'meter_label': 2, 'syllable_count': 2, 'is_full_anustubh': 2}

In [ ]:
# Verify Regex on Sample Labels

import re

VALID_LABEL_REGEX = re.compile(
    r"^anuṣṭubh \(\d,\d: (?!asamīcīna).+?[;,] \d,\d: (?!asamīcīna).+?\)$"
)

sample_labels = []

for verse in df["sa"].head(5):
    meter = mi.identify_meter(
        verse,
        from_scheme="DEV",
        resplit_option="resplit_max"
    )
    sample_labels.append(meter.meter_label)

print("=" * 70)
print("Regex Verification")
print("=" * 70)

for i, label in enumerate(sample_labels, 1):
    print(f"{i}. {label}")
    print("Match:", bool(VALID_LABEL_REGEX.match(label)))
    print()

======================================================================
Regex Verification
======================================================================
1. anuṣṭubh (1,2: pathyā; 3,4: pathyā)
Match: True

2. anuṣṭubh (1,2: pathyā; 3,4: pathyā)
Match: True

3. anuṣṭubh (1,2: pathyā; 3,4: pathyā)
Match: True

4. anuṣṭubh (1,2: pathyā; 3,4: pathyā)
Match: True

5. anuṣṭubh (1,2: ma-vipulā; 3,4: pathyā)
Match: True

In [ ]:

# Validate All Verses Using Skrutable
# ---------------------------------------

import pandas as pd
from tqdm.auto import tqdm

tqdm.pandas()

def analyze_verse(verse):
    try:
        meter = mi.identify_meter(
            verse,
            from_scheme="DEV",
            resplit_option="resplit_max"
        )

        label = meter.meter_label
        syllables = len(meter.syllable_weights.replace("\n", ""))

        return pd.Series({
            "meter_label": label,
            "syllable_count": syllables,
            "is_full_anustubh": bool(VALID_LABEL_REGEX.match(label)),
            "is_32_syllables": syllables == 32
        })

    except Exception:
        return pd.Series({
            "meter_label": "ERROR",
            "syllable_count": 0,
            "is_full_anustubh": False,
            "is_32_syllables": False
        })

print("=" * 70)
print("Validating Sanskrit verses...")
print("=" * 70)

results = df["sa"].progress_apply(analyze_verse)


df[
    [
        "meter_label",
        "syllable_count",
        "is_full_anustubh",
        "is_32_syllables"
    ]
] = results

print("\nValidation Complete")
print("=" * 70)

print(f"Full Anuṣṭubh : {int(df['is_full_anustubh'].sum())}")
print(f"32 Syllables  : {int(df['is_32_syllables'].sum())}")
print(f"Errors        : {int((df['meter_label'] == 'ERROR').sum())}")

checkpoint_path = OUTPUT_DIR / "03_validated_dataset.csv"

df.to_csv(checkpoint_path, index=False)

print("\nCheckpoint saved to:")
print(checkpoint_path)

======================================================================
Validating Sanskrit verses...
======================================================================

  0%|          | 0/32780 [00:00<?, ?it/s]

Validation Complete
======================================================================
Full Anuṣṭubh : 32614
32 Syllables  : 32614
Errors        : 0

Checkpoint saved to:
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/03_validated_dataset.csv

In [ ]:
# Create Final Filtered Dataset
# -----------------------------

filtered_df = df[df["is_full_anustubh"]].reset_index(drop=True)

print("=" * 70)
print("Filtered Dataset Created")
print("=" * 70)

print(f"Original Rows : {len(df)}")
print(f"Filtered Rows : {len(filtered_df)}")
print(f"Removed Rows  : {len(df) - len(filtered_df)}")

filtered_path = OUTPUT_DIR / "04_filtered_dataset.csv"
filtered_df.to_csv(filtered_path, index=False)

print("\n✅ Saved to:")
print(filtered_path)

======================================================================
Filtered Dataset Created
======================================================================
Original Rows : 32780
Filtered Rows : 32614
Removed Rows  : 166

✅ Saved to:
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/04_filtered_dataset.csv

In [ ]:
# Inspect Training Columns
# ------------------------

print("=" * 70)
print("Dataset Columns")
print("=" * 70)

print(filtered_df.columns.tolist())

print("\n")

print("=" * 70)
print("Sample Prompt")
print("=" * 70)

print(filtered_df["prompt"].iloc[0])

print("\n")

print("=" * 70)
print("Sample Sanskrit")
print("=" * 70)

print(filtered_df["sa"].iloc[0])

print("\n")

print("=" * 70)
print("Sample Hindi")
print("=" * 70)

print(filtered_df["hi"].iloc[0])

======================================================================
Dataset Columns
======================================================================
['sa', 'hi', 'meter', 'prompt', 'meter_label', 'syllable_count', 'is_full_anustubh', 'is_32_syllables']


======================================================================
Sample Prompt
======================================================================
The goal is to generate Sanskrit verse that follows the anushtup meter rules for the given input text.
RULES:
Verse Rules:
The verse contains 32 syllables/akshara and 4 padas in total.
The verse is divided into 2 lines, each containing 16 syllables.
Each line is divided into 2 padas (quartets), each containing exactly 8 syllables.
The fifth syllable of every pada must be LAGHU or short.
The sixth syllable of every pada must be GURU or long.
The seventh syllable of the second and fourth pada must be HRASVA.
The seventh syllable of the first and third pada must be DEERGHA.

Syllable Rules:
LAGHU vowels: अ, इ, उ, ऋ, ऌ
GURU vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ
HRASVA vowels: अ, इ, उ, ऋ, ऌ
DEERGHA vowels: आ, ई, ऊ, ॠ, ॡ, ए, ऐ, ओ, औ

Syllable classification rules:
- A syllable is marked Laghu/Guru and Hrasva/Deergha based on the vowel it contains.
- Any syllable containing anusvāra (ं) or visarga (ः) is always Guru.
- Any syllable followed by a conjunct consonant (saṁyuktākṣara) is always Guru.


======================================================================
Sample Sanskrit
======================================================================
न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्यार्थमुपयुञ्जीत धर्मं कामान् विसर्जयेत् ॥


======================================================================
Sample Hindi
======================================================================
इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह नहीं रखना चाहिये भोगों में जो आसक्ति होती है, वह दुःखरूप ही है धन पाकर भी उसे धर्ममें ही लगा देना चाहिये काम भोगोंको तो सर्वथा त्याग ही देना चाहिये

In [ ]:
# Prepare Filtered Dataset
# ---------------------------

final_df = filtered_df.copy()

print("=" * 70)
print("Filtered Dataset Ready")
print("=" * 70)

print(f"Total Samples : {len(final_df)}")

print("\nColumns:")
print(final_df.columns.tolist())

print("\nFirst Sample:")
display(final_df.head(1))

======================================================================
Filtered Dataset Ready
======================================================================
Total Samples : 32614

Columns:
['sa', 'hi', 'meter', 'prompt', 'meter_label', 'syllable_count', 'is_full_anustubh', 'is_32_syllables']

First Sample:

,sa,hi,meter,prompt,meter_label,syllable_count,is_full_anustubh,is_32_syllables
0,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True

# New Section

In [ ]:
#Create final_prompt
# ------------------

RULES = """
• The verse must follow the Anuṣṭubh meter.
• The verse must contain exactly 32 syllables.
• Output exactly four lines (one pāda per line).
• Use only Sanskrit in Devanagari script.
• Do not include explanations or extra text.
"""

def build_prompt(row):
    return f"""Objective:

Generate a Sanskrit verse in Anuṣṭubh meter based on a given meaning while strictly following the metrical rules.

Rules of Chandas:
{RULES}

Language:
The generated verse must be in Sanskrit in Devanagari script.
The input meaning is given in Hindi.
Do NOT include English words, transliteration, labels, or explanations.

Output Format:
(Output exactly 4 lines, one pada per line. Nothing else.)

Now generate the Sanskrit verse for the given Hindi meaning.

Meaning:
{row['hi']}

Sanskrit Verse:
"""

final_df["final_prompt"] = final_df.apply(build_prompt, axis=1)

print("=" * 70)
print("Final Prompt Column Created")
print("=" * 70)

print(final_df["final_prompt"].iloc[0])

======================================================================
Final Prompt Column Created
======================================================================
Objective:

Generate a Sanskrit verse in Anuṣṭubh meter based on a given meaning while strictly following the metrical rules.

Rules of Chandas:

• The verse must follow the Anuṣṭubh meter.
• The verse must contain exactly 32 syllables.
• Output exactly four lines (one pāda per line).
• Use only Sanskrit in Devanagari script.
• Do not include explanations or extra text.


Language:
The generated verse must be in Sanskrit in Devanagari script.
The input meaning is given in Hindi.
Do NOT include English words, transliteration, labels, or explanations.

Output Format:
(Output exactly 4 lines, one pada per line. Nothing else.)

Now generate the Sanskrit verse for the given Hindi meaning.

Meaning:
इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह नहीं रखना चाहिये भोगों में जो आसक्ति होती है, वह दुःखरूप ही है धन पाकर भी उसे धर्ममें ही लगा देना चाहिये काम भोगोंको तो सर्वथा त्याग ही देना चाहिये

Sanskrit Verse:

In [ ]:
#Save Final Dataset
#------------------

final_dataset_path = OUTPUT_DIR / "06_final_dataset.csv"

final_df.to_csv(
    final_dataset_path,
    index=False
)

print("=" * 70)
print("Final Dataset Saved Successfully")
print("=" * 70)

print(final_dataset_path)

======================================================================
Final Dataset Saved Successfully
======================================================================
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/06_final_dataset.csv

In [ ]:
#RECOVERY PART AFTER RUNTIME DISCONNECT

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
!pip -q install --upgrade pip

!pip -q install \
skrutable \
indic-transliteration \
pandas \
numpy \
tqdm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 30.7 MB/s eta 0:00:00

In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
PROJECT_NAME = "Sanskrit_Phi4_Finetuning"

BASE_DIR = Path("/content/drive/MyDrive") / PROJECT_NAME

OUTPUT_DIR = BASE_DIR / "outputs"

In [ ]:
filtered_df = pd.read_csv(
    OUTPUT_DIR / "04_filtered_dataset.csv"
)

print(filtered_df.shape)

display(filtered_df.head())

(32614, 8)

,sa,hi,meter,prompt,meter_label,syllable_count,is_full_anustubh,is_32_syllables
0,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True
1,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True
2,स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन...,वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर च...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True
3,अहोरात्रेक्षणो दिव्यो वेदाड़ः श्रुतिभूषण: आज्य...,"दिन और रात्रि उनके नेत्र हैं, वे दिव्यस्वरूप ह...",anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True
4,तथा हि दृड्डा बीभत्सुमुपायान्तं प्रशंसति यथा स...,तभी तो अर्जुन को आते देख ये उसकी प्रशंसा कर रह...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: ma-vipulā; 3,4: pathyā)",32,True,True

Task 2-4

In [ ]:
# ============================================================
# Task 2A - Load Final Dataset
# ============================================================

import pandas as pd
from pathlib import Path

PROJECT_DIR = Path("/content/drive/MyDrive/Sanskrit_Phi4_Finetuning")

DATASET_PATH = PROJECT_DIR / "outputs" / "06_final_dataset.csv"

df = pd.read_csv(DATASET_PATH)

print("=" * 70)
print("Dataset Loaded Successfully")
print("=" * 70)

print(f"Dataset Shape : {df.shape}")

print("\nColumns:")
print(df.columns.tolist())

display(df.head())

======================================================================
Dataset Loaded Successfully
======================================================================
Dataset Shape : (32614, 9)

Columns:
['sa', 'hi', 'meter', 'prompt', 'meter_label', 'syllable_count', 'is_full_anustubh', 'is_32_syllables', 'final_prompt']

,sa,hi,meter,prompt,meter_label,syllable_count,is_full_anustubh,is_32_syllables,final_prompt
0,न कामाननुरुद्ध्येत दुःखं कामेषु वै रतिः प्राप्...,इसलिये कामनाओं या भोगोंकी वृद्धिके लिये आग्रह ...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True,Objective:\n\nGenerate a Sanskrit verse in Anu...
1,यज्ञशिष्टाशिनः सन्तो मुच्यन्ते सर्वकिल्बिषैः भ...,कारण कि यज्ञसे शेष बचे हुए अन्नको खानेवाले श्र...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True,Objective:\n\nGenerate a Sanskrit verse in Anu...
2,स देवप्रस्थमासाद्य सेनाविन्दोः पुरं प्रति बलेन...,वहाँसे सेनाविन्दुकी राजधानी देवप्रश्वमें आकर च...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True,Objective:\n\nGenerate a Sanskrit verse in Anu...
3,अहोरात्रेक्षणो दिव्यो वेदाड़ः श्रुतिभूषण: आज्य...,"दिन और रात्रि उनके नेत्र हैं, वे दिव्यस्वरूप ह...",anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: pathyā; 3,4: pathyā)",32,True,True,Objective:\n\nGenerate a Sanskrit verse in Anu...
4,तथा हि दृड्डा बीभत्सुमुपायान्तं प्रशंसति यथा स...,तभी तो अर्जुन को आते देख ये उसकी प्रशंसा कर रह...,anuṣṭubh,The goal is to generate Sanskrit verse that fo...,"anuṣṭubh (1,2: ma-vipulā; 3,4: pathyā)",32,True,True,Objective:\n\nGenerate a Sanskrit verse in Anu...

In [ ]:
# ============================================================
# Task 2B - Create Train / Validation / Test Split (90:5:5)
# ============================================================

import json
from pathlib import Path
from sklearn.model_selection import train_test_split

# ------------------------------------------------------------
# Reproducibility
# ------------------------------------------------------------
SEED = 42

# ------------------------------------------------------------
# Required Columns
# ------------------------------------------------------------
INSTRUCTION_COL = "final_prompt"
INPUT_COL = "hi"
OUTPUT_COL = "sa"

# Keep only required columns
dataset = df[[INSTRUCTION_COL, INPUT_COL, OUTPUT_COL]].copy()

# Rename columns for training
dataset.columns = ["instruction", "input", "output"]

# ------------------------------------------------------------
# Train (90%) | Temp (10%)
# ------------------------------------------------------------
train_df, temp_df = train_test_split(
    dataset,
    test_size=0.10,
    random_state=SEED,
    shuffle=True,
)

# ------------------------------------------------------------
# Validation (5%) | Test (5%)
# ------------------------------------------------------------
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=SEED,
    shuffle=True,
)

# ------------------------------------------------------------
# Save Dataset Splits
# ------------------------------------------------------------
SPLIT_DIR = PROJECT_DIR / "outputs" / "dataset_splits"
SPLIT_DIR.mkdir(parents=True, exist_ok=True)

train_df.to_csv(SPLIT_DIR / "train.csv", index=False)
val_df.to_csv(SPLIT_DIR / "validation.csv", index=False)
test_df.to_csv(SPLIT_DIR / "test.csv", index=False)

# ------------------------------------------------------------
# Save Split Configuration
# ------------------------------------------------------------
split_config = {
    "seed": SEED,
    "train_ratio": 0.90,
    "validation_ratio": 0.05,
    "test_ratio": 0.05,
    "instruction_column": "instruction",
    "input_column": "input",
    "output_column": "output",
}

with open(SPLIT_DIR / "split_config.json", "w") as f:
    json.dump(split_config, f, indent=4)

# ------------------------------------------------------------
# Display Summary
# ------------------------------------------------------------
print("=" * 70)
print("Dataset Split Completed Successfully")
print("=" * 70)

print(f"Total Samples      : {len(dataset):,}")
print(f"Training Samples   : {len(train_df):,}")
print(f"Validation Samples : {len(val_df):,}")
print(f"Test Samples       : {len(test_df):,}")

print("\nFiles Saved To:")
print(SPLIT_DIR)

======================================================================
Dataset Split Completed Successfully
======================================================================
Total Samples      : 32,614
Training Samples   : 29,352
Validation Samples : 1,631
Test Samples       : 1,631

Files Saved To:
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/dataset_splits

In [ ]:
# ============================================================
# Task 3A - Create Reproducible Configuration Files
# ============================================================

import json
from pathlib import Path

CONFIG_DIR = PROJECT_DIR / "outputs" / "config"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)

# ------------------------------------------------------------
# Seed Configuration
# ------------------------------------------------------------
seed_config = {
    "seed": 42
}

# ------------------------------------------------------------
# LoRA Configuration
# ------------------------------------------------------------
lora_config = {
    "r": 8,
    "lora_alpha": 16,
    "lora_dropout": 0.05,
    "bias": "none",
    "task_type": "CAUSAL_LM"
}

# ------------------------------------------------------------
# Training Configuration
# ------------------------------------------------------------
training_config = {
    "model_name": "microsoft/Phi-4-mini-instruct",
    "load_in_4bit": True,
    "max_seq_length": 2048,
    "train_batch_size": 2,
    "eval_batch_size": 2,
    "gradient_accumulation_steps": 8,
    "learning_rate": 2e-4,
    "weight_decay": 0.01,
    "num_train_epochs": 3,
    "warmup_ratio": 0.03,
    "lr_scheduler_type": "cosine",
    "logging_steps": 10,
    "evaluation_strategy": "steps",
    "save_strategy": "steps",
    "load_best_model_at_end": True,
    "metric_for_best_model": "eval_loss",
    "greater_is_better": False,
    "seed": 42
}

# ------------------------------------------------------------
# Save JSON Files
# ------------------------------------------------------------
with open(CONFIG_DIR / "seed_config.json", "w") as f:
    json.dump(seed_config, f, indent=4)

with open(CONFIG_DIR / "lora_config.json", "w") as f:
    json.dump(lora_config, f, indent=4)

with open(CONFIG_DIR / "training_config.json", "w") as f:
    json.dump(training_config, f, indent=4)

print("=" * 70)
print("Configuration Files Saved Successfully")
print("=" * 70)

print(f"Seed Config      : {CONFIG_DIR/'seed_config.json'}")
print(f"LoRA Config      : {CONFIG_DIR/'lora_config.json'}")
print(f"Training Config  : {CONFIG_DIR/'training_config.json'}")

======================================================================
Configuration Files Saved Successfully
======================================================================
Seed Config      : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/config/seed_config.json
LoRA Config      : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/config/lora_config.json
Training Config  : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/config/training_config.json

In [ ]:
# ============================================================
# Task 3B - Environment Setup and Reproducibility
# ============================================================

import os
import random
import numpy as np
import torch

SEED = 42

# Python
random.seed(SEED)

# NumPy
np.random.seed(SEED)

# PyTorch
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed(SEED)
    torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

os.environ["PYTHONHASHSEED"] = str(SEED)

print("=" * 70)
print("Reproducibility Enabled")
print("=" * 70)

print("Seed :", SEED)
print("CUDA :", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU  :", torch.cuda.get_device_name(0))

======================================================================
Reproducibility Enabled
======================================================================
Seed : 42
CUDA : True
GPU  : Tesla T4

In [ ]:
# ============================================================
# Task 3C - Load Phi-4 Mini Instruct (4-bit)
# ============================================================

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
)

MODEL_NAME = "microsoft/Phi-4-mini-instruct"

# ------------------------------------------------------------
# BitsAndBytes Configuration
# ------------------------------------------------------------
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
)

print("=" * 70)
print("Loading Tokenizer...")
print("=" * 70)

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

print("=" * 70)
print("Loading Model...")
print("=" * 70)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    trust_remote_code=False,      # IMPORTANT
)

model.config.use_cache = False

print("=" * 70)
print("Model Loaded Successfully")
print("=" * 70)

print("Model :", MODEL_NAME)
print("Device:", next(model.parameters()).device)
print("Dtype :", next(model.parameters()).dtype)

======================================================================
Loading Tokenizer...
======================================================================

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

======================================================================
Loading Model...
======================================================================

model.safetensors.index.json:   0%|          | 0.00/16.3k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/194 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/bitsandbytes/backends/cuda/ops.py:213: FutureWarning: _check_is_size will be removed in a future PyTorch release along with guard_size_oblivious.     Use _check(i >= 0) instead.
  torch._check_is_size(blocksize)

generation_config.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

======================================================================
Model Loaded Successfully
======================================================================
Model : microsoft/Phi-4-mini-instruct
Device: cuda:0
Dtype : torch.float16

In [ ]:
# ============================================================
# Task 3D - Configure LoRA for Phi-4 Mini Instruct
# ============================================================

from peft import LoraConfig, get_peft_model, TaskType

# ------------------------------------------------------------
# LoRA Configuration
# ------------------------------------------------------------
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules="all-linear",
)

print("=" * 70)
print("Applying LoRA...")
print("=" * 70)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

print("=" * 70)
print("LoRA Applied Successfully")
print("=" * 70)

======================================================================
Applying LoRA...
======================================================================
trainable params: 11,534,336 || all params: 3,847,556,096 || trainable%: 0.2998
======================================================================
LoRA Applied Successfully
======================================================================

In [ ]:
# ============================================================
# Task 3E - Load and Prepare Training Dataset
# ============================================================

from pathlib import Path
import pandas as pd
from datasets import Dataset

# ------------------------------------------------------------
# Recreate Project Paths
# ------------------------------------------------------------
PROJECT_DIR = Path("/content/drive/MyDrive/Sanskrit_Phi4_Finetuning")
OUTPUT_DIR = PROJECT_DIR / "outputs"

# ------------------------------------------------------------
# Dataset Paths
# ------------------------------------------------------------
TRAIN_PATH = OUTPUT_DIR / "dataset_splits" / "train.csv"
VALID_PATH = OUTPUT_DIR / "dataset_splits" / "validation.csv"

print("Train Path :", TRAIN_PATH)
print("Valid Path :", VALID_PATH)

# ------------------------------------------------------------
# Verify Files Exist
# ------------------------------------------------------------
assert TRAIN_PATH.exists(), f"Missing: {TRAIN_PATH}"
assert VALID_PATH.exists(), f"Missing: {VALID_PATH}"

# ------------------------------------------------------------
# Load CSV Files
# ------------------------------------------------------------
train_df = pd.read_csv(TRAIN_PATH)
valid_df = pd.read_csv(VALID_PATH)

print("\n" + "=" * 70)
print("Dataset Loaded Successfully")
print("=" * 70)

print(f"Training Samples   : {len(train_df):,}")
print(f"Validation Samples : {len(valid_df):,}")

display(train_df.head())

# ------------------------------------------------------------
# Convert to HuggingFace Dataset
# ------------------------------------------------------------
train_dataset = Dataset.from_pandas(train_df, preserve_index=False)
valid_dataset = Dataset.from_pandas(valid_df, preserve_index=False)

print("\nConversion Successful")
print(train_dataset)
print(valid_dataset)

Train Path : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/dataset_splits/train.csv
Valid Path : /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs/dataset_splits/validation.csv

======================================================================
Dataset Loaded Successfully
======================================================================
Training Samples   : 29,352
Validation Samples : 1,631

,instruction,input,output
0,Objective:\n\nGenerate a Sanskrit verse in Anu...,भरतवंशके सिंह युधिष्ठिर ! समस्त न्यायालयोंमें ...,प्रत्यक्षाश्च परोक्षाश्च सर्वाधिकरणेष्वथ वृत्त...
1,Objective:\n\nGenerate a Sanskrit verse in Anu...,पत्थरोंके गोले बरसानेवाले यन्त्र लगा दिये जाय॑...,अष्मयन्त्राणि युज्यन्तां क्षेपणीयाश्व मुद्गरा:...
2,Objective:\n\nGenerate a Sanskrit verse in Anu...,उस महाबाहु मेघको देखते ही ब्राह्मणके मनमें उसक...,दृष्ट्वैव तं महाबाहुं तस्य भक्तिरजायत अयं मे ध...
3,Objective:\n\nGenerate a Sanskrit verse in Anu...,मैंने उस मन्दबुद्धि राजा जरासंधसे कहा था कि अर...,उक्तश्चैष मया राजा जरासंधोऽल्पवेतनः कृष्णाद् व...
4,Objective:\n\nGenerate a Sanskrit verse in Anu...,"ब्राह्मणसे उसका 'कुशल' पूछना चाहिये, इसी प्रका...",ब्राह्मणं कुशलं पृच्छेत् क्षत्रबन्धुमनामयम् वै...

Conversion Successful
Dataset({
    features: ['instruction', 'input', 'output'],
    num_rows: 29352
})
Dataset({
    features: ['instruction', 'input', 'output'],
    num_rows: 1631
})

In [ ]:
# ============================================================
# Task 3F - Format Dataset for Phi-4 Training
# ============================================================

def format_example(example):
    text = (
        f"<|user|>\n"
        f"{example['instruction']}\n\n"
        f"Hindi Meaning:\n{example['input']}\n"
        f"<|end|>\n"
        f"<|assistant|>\n"
        f"{example['output']}\n"
        f"<|end|>"
    )

    return {"text": text}


train_dataset = train_dataset.map(format_example)
valid_dataset = valid_dataset.map(format_example)

print("=" * 70)
print("Dataset Formatted Successfully")
print("=" * 70)

print(train_dataset)

print("\nSample Training Example:\n")
print(train_dataset[0]["text"])

Map:   0%|          | 0/29352 [00:00<?, ? examples/s]

Map:   0%|          | 0/1631 [00:00<?, ? examples/s]

======================================================================
Dataset Formatted Successfully
======================================================================
Dataset({
    features: ['instruction', 'input', 'output', 'text'],
    num_rows: 29352
})

Sample Training Example:

<|user|>
Objective:

Generate a Sanskrit verse in Anuṣṭubh meter based on a given meaning while strictly following the metrical rules.

Rules of Chandas:

• The verse must follow the Anuṣṭubh meter.
• The verse must contain exactly 32 syllables.
• Output exactly four lines (one pāda per line).
• Use only Sanskrit in Devanagari script.
• Do not include explanations or extra text.


Language:
The generated verse must be in Sanskrit in Devanagari script.
The input meaning is given in Hindi.
Do NOT include English words, transliteration, labels, or explanations.

Output Format:
(Output exactly 4 lines, one pada per line. Nothing else.)

Now generate the Sanskrit verse for the given Hindi meaning.

Meaning:
भरतवंशके सिंह युधिष्ठिर ! समस्त न्यायालयोंमें जो प्रत्यक्ष और परोक्ष विचार होते हैं तथा वहाँ जो राजकीय पुरुषोंके व्यवहार होते हैं, उन सबका प्रतिदिन निरीक्षण करना चाहिये इसका भी उक्त शास्त्रमें उल्लेख है

Sanskrit Verse:


Hindi Meaning:
भरतवंशके सिंह युधिष्ठिर ! समस्त न्यायालयोंमें जो प्रत्यक्ष और परोक्ष विचार होते हैं तथा वहाँ जो राजकीय पुरुषोंके व्यवहार होते हैं, उन सबका प्रतिदिन निरीक्षण करना चाहिये इसका भी उक्त शास्त्रमें उल्लेख है
<|end|>
<|assistant|>
प्रत्यक्षाश्च परोक्षाश्च सर्वाधिकरणेष्वथ वृत्तेर्भरतशार्दूल नित्यं चैवान्ववेक्षणम् ॥
<|end|>

In [ ]:
# ============================================================
# Task 3G - Configure the Trainer
# ============================================================

from pathlib import Path
from transformers import TrainingArguments

# ------------------------------------------------------------
# Project Directories
# ------------------------------------------------------------
PROJECT_DIR = Path("/content/drive/MyDrive/Sanskrit_Phi4_Finetuning")

CHECKPOINT_DIR = PROJECT_DIR / "models" / "phi4_lora_checkpoints"
LOG_DIR = PROJECT_DIR / "logs" / "tensorboard"

CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
LOG_DIR.mkdir(parents=True, exist_ok=True)

training_args = TrainingArguments(
    output_dir=str(CHECKPOINT_DIR),

    num_train_epochs=3,

    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,

    gradient_accumulation_steps=16,

    learning_rate=2e-4,
    weight_decay=0.01,

    logging_dir=str(LOG_DIR),
    logging_strategy="steps",
    logging_steps=25,

    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    save_total_limit=2,

    fp16=True,

    report_to="tensorboard",

    seed=42,

    remove_unused_columns=False,
)

print("=" * 70)
print("TrainingArguments Created Successfully")
print("=" * 70)

print(training_args)

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

======================================================================
TrainingArguments Created Successfully
======================================================================
TrainingArguments(
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_static_graph=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
enable_jit_checkpoint=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=True,
fp16_full_eval=False,
fsdp=None,
fsdp_config=None,
full_determinism=False,
gradient_accumulation_steps=16,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_num_input_tokens_seen=no,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0002,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=-1,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/logs/tensorboard,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=25,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs=None,
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=eval_loss,
neftune_noise_alpha=None,
num_train_epochs=3,
optim=OptimizerNames.ADAMW_TORCH_FUSED,
optim_args=None,
optim_target_modules=None,
output_dir=/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/models/phi4_lora_checkpoints,
parallelism_config=None,
per_device_eval_batch_size=1,
per_device_train_batch_size=1,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
remove_unused_columns=False,
report_to=['tensorboard'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=2,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
trackio_bucket_id=None,
trackio_space_id=None,
trackio_static_space_id=None,
train_sampling_strategy=random,
use_cache=False,
use_cpu=False,
use_liger_kernel=False,
warmup_ratio=None,
warmup_steps=0,
weight_decay=0.01,
)

In [ ]:
# ============================================================
# Task 3H - Create the SFT Trainer
# ============================================================

from trl import SFTTrainer

def formatting_func(example):
    return example["text"]

trainer = SFTTrainer(
    model=model,                     # Already a PeftModel
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=valid_dataset,
    processing_class=tokenizer,
    formatting_func=formatting_func,
)

print("=" * 70)
print("SFT Trainer Created Successfully")
print("=" * 70)

print(type(trainer))

[transformers] `logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

Applying formatting function to train dataset:   0%|          | 0/29352 [00:00<?, ? examples/s]

Adding EOS to train dataset:   0%|          | 0/29352 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/29352 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/29352 [00:00<?, ? examples/s]

Truncating train dataset:   0%|          | 0/29352 [00:00<?, ? examples/s]

Applying formatting function to eval dataset:   0%|          | 0/1631 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/1631 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/1631 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/1631 [00:00<?, ? examples/s]

Truncating eval dataset:   0%|          | 0/1631 [00:00<?, ? examples/s]

======================================================================
SFT Trainer Created Successfully
======================================================================
<class 'trl.trainer.sft_trainer.SFTTrainer'>

In [ ]:
print(trainer.args.half_precision_backend)

AttributeError: 'SFTConfig' object has no attribute 'half_precision_backend'

In [ ]:
#RECOVERY
#---------

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip cache purge

Files removed: 114

In [ ]:
!pip install -U \
torch==2.6.0 \
torchvision==0.21.0 \
torchaudio==2.6.0

Collecting torch==2.6.0
  Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Collecting torchvision==0.21.0
  Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio==2.6.0
  Downloading torchaudio-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (4.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.1.6)
Collecting fsspec (from torch==2.6.0)
  Downloading fsspec-2026.6.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (1.13.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision==0.21.0) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision==0.21.0) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch==2.6.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.6.0) (3.0.3)
Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl (766.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.6/766.6 MB 1.5 MB/s eta 0:00:00
Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 126.7 MB/s eta 0:00:00
Downloading torchaudio-2.6.0-cp312-cp312-manylinux1_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 122.7 MB/s eta 0:00:00
Downloading fsspec-2026.6.0-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.9/203.9 kB 20.4 MB/s eta 0:00:00
Installing collected packages: fsspec, torch, torchvision, torchaudio
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
timm 1.0.28 requires huggingface_hub, which is not installed.
timm 1.0.28 requires safetensors, which is not installed.
gradio-client 2.5.0 requires huggingface-hub<2.0,>=0.19.3, which is not installed.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.6.0 which is incompatible.
Successfully installed fsspec-2026.6.0 torch-2.6.0 torchaudio-2.6.0 torchvision-0.21.0

In [ ]:
!pip install flash-attn==2.7.4.post1 --no-build-isolation

Collecting flash-attn==2.7.4.post1
  Downloading flash_attn-2.7.4.post1.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 89.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.7.4.post1) (2.6.0)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.7.4.post1) (0.8.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (4.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (2024.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (3.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch->flash-attn==2.7.4.post1) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch->flash-attn==2.7.4.post1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->flash-attn==2.7.4.post1) (3.0.3)
Building wheels for collected packages: flash-attn
  Building wheel for flash-attn (setup.py) ... done
  Created wheel for flash-attn: filename=flash_attn-2.7.4.post1-cp312-cp312-linux_x86_64.whl size=187826523 sha256=7e0b07913d56782d0f3f2ee76bd39587557742628983f6ab9ec2527c99437476
  Stored in directory: /root/.cache/pip/wheels/48/0f/98/166bf6b39dd0592924b22ce21b799fc9fd76c3a302c12ee359
Successfully built flash-attn
Installing collected packages: flash-attn
Successfully installed flash-attn-2.7.4.post1

In [ ]:
!pip show torchao

Name: torchao
Version: 0.17.0
Summary: Package for applying ao techniques to GPU models
Home-page: https://github.com/pytorch/ao
Author:
Author-email:
License:
Location: /usr/local/lib/python3.12/dist-packages
Requires:
Required-by: unsloth_zoo

In [ ]:
!pip uninstall -y torchao

Found existing installation: torchao 0.17.0
Uninstalling torchao-0.17.0:
  Successfully uninstalled torchao-0.17.0

In [ ]:
!pip list | grep torch

torch                                 2.6.0
torchaudio                            2.6.0
torchcodec                            0.11.0+cu128
torchdata                             0.11.0
torchsummary                          1.5.1
torchvision                           0.21.0

In [ ]:
!pip show transformers

Name: transformers
Version: 5.5.0
Summary: Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training.
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /usr/local/lib/python3.12/dist-packages
Requires: huggingface-hub, numpy, packaging, pyyaml, regex, safetensors, tokenizers, tqdm, typer
Required-by: peft, sentence-transformers, trl, unsloth_zoo

In [ ]:
!pip uninstall -y \
transformers \
trl \
peft \
accelerate \
huggingface-hub \
tokenizers \
torchcodec \
torchdata

Found existing installation: transformers 5.5.0
Uninstalling transformers-5.5.0:
  Successfully uninstalled transformers-5.5.0
Found existing installation: trl 0.24.0
Uninstalling trl-0.24.0:
  Successfully uninstalled trl-0.24.0
Found existing installation: peft 0.19.1
Uninstalling peft-0.19.1:
  Successfully uninstalled peft-0.19.1
Found existing installation: accelerate 1.4.0
Uninstalling accelerate-1.4.0:
  Successfully uninstalled accelerate-1.4.0
Found existing installation: huggingface_hub 1.24.0
Uninstalling huggingface_hub-1.24.0:
  Successfully uninstalled huggingface_hub-1.24.0
Found existing installation: tokenizers 0.22.2
Uninstalling tokenizers-0.22.2:
  Successfully uninstalled tokenizers-0.22.2
Found existing installation: torchcodec 0.11.0+cu128
Uninstalling torchcodec-0.11.0+cu128:
  Successfully uninstalled torchcodec-0.11.0+cu128
Found existing installation: torchdata 0.11.0
Uninstalling torchdata-0.11.0:
  Successfully uninstalled torchdata-0.11.0

In [ ]:
!pip install \
transformers==4.49.0 \
trl==0.15.2 \
peft==0.14.0 \
accelerate==1.4.0 \
huggingface-hub==0.29.3 \
tokenizers==0.21.0

Requirement already satisfied: transformers==4.49.0 in /usr/local/lib/python3.12/dist-packages (4.49.0)
Requirement already satisfied: trl==0.15.2 in /usr/local/lib/python3.12/dist-packages (0.15.2)
Requirement already satisfied: peft==0.14.0 in /usr/local/lib/python3.12/dist-packages (0.14.0)
Requirement already satisfied: accelerate==1.4.0 in /usr/local/lib/python3.12/dist-packages (1.4.0)
Requirement already satisfied: huggingface-hub==0.29.3 in /usr/local/lib/python3.12/dist-packages (0.29.3)
Requirement already satisfied: tokenizers==0.21.0 in /usr/local/lib/python3.12/dist-packages (0.21.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (3.29.7)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (2.32.4)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0) (4.67.3)
Requirement already satisfied: datasets>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from trl==0.15.2) (4.3.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from trl==0.15.2) (13.9.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft==0.14.0) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.14.0) (2.6.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.29.3) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub==0.29.3) (4.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->trl==0.15.2) (25.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->trl==0.15.2) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->trl==0.15.2) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->trl==0.15.2) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->trl==0.15.2) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.21.0->trl==0.15.2) (0.70.16)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.49.0) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.49.0) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.49.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.49.0) (2026.6.17)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (3.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.14.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch>=1.13.0->peft==0.14.0) (1.3.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->trl==0.15.2) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->trl==0.15.2) (2.20.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.21.0->trl==0.15.2) (4.14.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=2.21.0->trl==0.15.2) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.21.0->trl==0.15.2) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->trl==0.15.2) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft==0.14.0) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0->trl==0.15.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0->trl==0.15.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=2.21.0->trl==0.15.2) (2026.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=2.21.0->trl==0.15.2) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=2.21.0->trl==0.15.2) (1.17.0)

In [ ]:
!pip show transformers

Name: transformers
Version: 4.49.0
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /usr/local/lib/python3.12/dist-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: peft, sentence-transformers, trl, unsloth_zoo

In [ ]:
import torch
import transformers
import trl
import peft
import accelerate
import datasets
import bitsandbytes as bnb

print("Torch        :", torch.__version__)
print("Transformers :", transformers.__version__)
print("TRL          :", trl.__version__)
print("PEFT         :", peft.__version__)
print("Accelerate   :", accelerate.__version__)
print("Datasets     :", datasets.__version__)
print("BitsAndBytes :", bnb.__version__)

Torch        : 2.6.0+cu124
Transformers : 4.49.0
TRL          : 0.15.2
PEFT         : 0.14.0
Accelerate   : 1.4.0
Datasets     : 4.3.0
BitsAndBytes : 0.45.5

In [ ]:
!pip list | grep -E "torchao|torchcodec|torchdata|flash|unsloth"

flash_attn                            2.7.4.post1
unsloth                               2026.7.5
unsloth_zoo                           2026.7.6

In [ ]:
#CHECKING IF FLASH ATTENTION 2 ACTUALLY WORKING
#----------------------------------------------
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model_name = "microsoft/Phi-4-mini-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    attn_implementation="flash_attention_2",
    torch_dtype=torch.float16,
    device_map="auto",
)

print("✅ Model loaded successfully!")
print("Attention implementation:", model.config._attn_implementation)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/15.5M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/249 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/587 [00:00<?, ?B/s]

config.json: 0.00B [00:00, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.90G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/2.77G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

✅ Model loaded successfully!
Attention implementation: flash_attention_2

In [ ]:
print(model.config._attn_implementation)

flash_attention_2

In [ ]:
#REQUIREMENTS FILE
#--------------------

from google.colab import drive
drive.mount('/content/drive')

PROJECT_DIR = "/content/drive/MyDrive/Sanskrit_Phi4_Finetuning"

requirements = """\
torch==2.6.0
torchvision==0.21.0
torchaudio==2.6.0

transformers==4.49.0
trl==0.15.2
peft==0.14.0
accelerate==1.4.0
datasets==4.3.0
bitsandbytes==0.45.5

flash-attn==2.7.4.post1

sentencepiece
evaluate
tensorboard
"""

with open(f"{PROJECT_DIR}/requirements.txt", "w") as f:
    f.write(requirements)

print("✅ requirements.txt saved to Google Drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
✅ requirements.txt saved to Google Drive

In [ ]:
import torch

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!pip install -r "/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt"

Requirement already satisfied: torch==2.6.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: torchvision==0.21.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 2)) (0.21.0)
Requirement already satisfied: torchaudio==2.6.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 3)) (2.6.0)
Requirement already satisfied: transformers==4.49.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (4.49.0)
Requirement already satisfied: trl==0.15.2 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 6)) (0.15.2)
Requirement already satisfied: peft==0.14.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 7)) (0.14.0)
Requirement already satisfied: accelerate==1.4.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: datasets==4.3.0 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (4.3.0)
Requirement already satisfied: bitsandbytes==0.45.5 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 10)) (0.45.5)
Requirement already satisfied: flash-attn==2.7.4.post1 in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 12)) (2.7.4.post1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 14)) (0.2.2)
Requirement already satisfied: evaluate in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 15)) (0.4.6)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (from -r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (2.21.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (3.29.7)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (2024.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision==0.21.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision==0.21.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 2)) (11.3.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (0.29.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (2.32.4)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (4.67.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from trl==0.15.2->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 6)) (13.9.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft==0.14.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 7)) (5.9.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (25.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (2.2.2)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (0.70.16)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from flash-attn==2.7.4.post1->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 12)) (0.8.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch==2.6.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (1.4.0)
Requirement already satisfied: grpcio<2.0,>=1.74.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (1.82.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (3.10.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (7.35.1)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (3.1.8)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.49.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 5)) (2.5.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 16)) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (2026.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->trl==0.15.2->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 6)) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->trl==0.15.2->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 6)) (2.20.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (1.24.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->trl==0.15.2->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 6)) (0.1.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets==4.3.0->-r /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt (line 9)) (1.17.0)

In [ ]:
!pip list | grep -E "unsloth|trl|transformers|torch|peft|accelerate|flash"

accelerate                            1.4.0
flash_attn                            2.7.4.post1
peft                                  0.14.0
sentence-transformers                 5.6.1
torch                                 2.6.0
torchaudio                            2.6.0
torchsummary                          1.5.1
torchvision                           0.21.0
transformers                          4.49.0
trl                                   0.15.2
unsloth                               2026.7.5
unsloth_zoo                           2026.7.6

In [ ]:
!pip install -U \
trl==0.19.0 \
peft==0.17.1 \
accelerate==1.7.0

Requirement already satisfied: trl==0.19.0 in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: peft==0.17.1 in /usr/local/lib/python3.12/dist-packages (0.17.1)
Requirement already satisfied: accelerate==1.7.0 in /usr/local/lib/python3.12/dist-packages (1.7.0)
Requirement already satisfied: datasets>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from trl==0.19.0) (4.3.0)
Requirement already satisfied: transformers>=4.51.0 in /usr/local/lib/python3.12/dist-packages (from trl==0.19.0) (5.14.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (26.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (2.6.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (4.67.3)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (0.8.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.17.1) (1.24.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (3.29.7)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (25.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (3.8.1)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets>=3.0.0->trl==0.19.0) (0.70.16)
Requirement already satisfied: fsspec<=2025.9.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (2024.9.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft==0.17.1) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft==0.17.1) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub>=0.25.0->peft==0.17.1) (4.16.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (3.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft==0.17.1) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch>=1.13.0->peft==0.17.1) (1.3.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0->trl==0.19.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0->trl==0.19.0) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.51.0->trl==0.19.0) (0.26.8)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl==0.19.0) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl==0.19.0) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl==0.19.0) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets>=3.0.0->trl==0.19.0) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets>=3.0.0->trl==0.19.0) (0.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl==0.19.0) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets>=3.0.0->trl==0.19.0) (2.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft==0.17.1) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl==0.19.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl==0.19.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets>=3.0.0->trl==0.19.0) (2026.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0->trl==0.19.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0->trl==0.19.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.51.0->trl==0.19.0) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.9.0,>=2023.1.0->datasets>=3.0.0->trl==0.19.0) (1.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets>=3.0.0->trl==0.19.0) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.51.0->trl==0.19.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.51.0->trl==0.19.0) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.51.0->trl==0.19.0) (0.1.2)

In [ ]:
import sys
import torch

print("Python:", sys.version)
print("Torch:", torch.__version__)
print("CUDA:", torch.version.cuda)
!nvidia-smi

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]
Torch: 2.6.0+cu124
CUDA: 12.4
Fri Jul 24 10:28:53 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8             10W /   70W |       3MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [ ]:
!wget -qO- https://raw.githubusercontent.com/unslothai/unsloth/main/unsloth/_auto_install.py | python -

Traceback (most recent call last):
  File "<stdin>", line 39, in <module>
RuntimeError: Torch = 2.11.0 too new!

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128

In [ ]:
# Fresh runtime first: Runtime -> Disconnect and delete runtime -> reconnect, GPU on.
!pip uninstall -y gradio gcsfs -q

# torch first, pinned exactly (foundational, rarely conflicts with anything downstream)
!pip install -q torch==2.11.0 torchvision==0.26.0 torchaudio==2.11.0 \
    --index-url https://download.pytorch.org/whl/cu128

# Now install unsloth from the exact commit your instructor used --
# WITHOUT also forcing exact peft/transformers/trl/unsloth_zoo pins in the
# same line. Let pip resolve whatever versions THIS commit of unsloth
# actually needs -- that's what avoids the conflict.
!pip install -q "unsloth @ git+https://github.com/unslothai/unsloth.git@e55d0e6c75437af79f3338aca1ec12c7ea16e3bd"

# Eval-only extras (not part of instructor's stack, needed for grading metrics)
!pip install -q sentence-transformers skrutable

WARNING: Skipping gradio as it is not installed.
WARNING: Skipping gcsfs as it is not installed.

# small test

In [ ]:
# Just install unsloth plain -- it picks compatible torch/transformers/peft/
# accelerate versions on its own. This is the current officially recommended way.
!pip install -q unsloth

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.8/66.8 kB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 11.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 24.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.8/506.8 kB 21.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 91.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 423.1/423.1 kB 23.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 62.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 42.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 77.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.0/215.0 kB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 65.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 225.0/225.0 kB 19.4 MB/s eta 0:00:00

In [ ]:
# unsloth doesn't always pull trl in automatically -- install explicitly.
!pip install -q trl sentence-transformers skrutable

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.2/85.2 kB 4.5 MB/s eta 0:00:00

In [ ]:
# Verify everything imports cleanly before doing anything else.
import torch, transformers, trl, peft, accelerate, unsloth, datasets, bitsandbytes

print("torch:", torch.__version__)
print("transformers:", transformers.__version__)
print("trl:", trl.__version__)
print("peft:", peft.__version__)
print("accelerate:", accelerate.__version__)
print("bitsandbytes:", bitsandbytes.__version__)
print("datasets:", datasets.__version__)
print("unsloth:", unsloth.__version__)
print("GPU:", torch.cuda.get_device_name(0), "| capability:", torch.cuda.get_device_capability(0))

ATTN_IMPL = "sdpa"  # no flash-attn for this run -- confirmed T4, per your instructor's note
print("attn_implementation:", ATTN_IMPL)

WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_cutlass_90a.abi3.so
WARNING:torchao:Failed to load /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.12/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
/usr/local/lib/python3.12/dist-packages/unsloth/__init__.py:1432: UserWarning: WARNING: Unsloth should be imported before [trl, transformers, peft] to ensure all optimizations are applied. Your code may run slower or encounter memory issues without these optimizations.

Please restructure your imports with 'import unsloth' at the top of your file.
  from ._gpu_init import *

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
torch: 2.11.0+cu128
transformers: 5.5.0
trl: 0.24.0
peft: 0.19.1
accelerate: 1.14.0
bitsandbytes: 0.50.0
datasets: 4.3.0
unsloth: 2026.7.5
GPU: Tesla T4 | capability: (7, 5)
attn_implementation: sdpa

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
PROJECT_DIR = Path("/content/drive/MyDrive/Sanskrit_Phi4_Finetuning")
SPLIT_DIR  = PROJECT_DIR / "outputs" / "dataset_splits"
CONFIG_DIR = PROJECT_DIR / "outputs" / "config"
MODEL_DIR  = PROJECT_DIR / "models"
OUTPUT_DIR = PROJECT_DIR / "outputs" / "generation_results"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

for f in ["train.csv", "validation.csv", "test.csv"]:
    assert (SPLIT_DIR / f).exists(), f"Missing {SPLIT_DIR/f}"
for f in ["lora_config.json", "seed_config.json", "training_config.json"]:
    assert (CONFIG_DIR / f).exists(), f"Missing {CONFIG_DIR/f}"
print("All paths verified OK.")

Mounted at /content/drive
All paths verified OK.

In [ ]:
import json, random, os
import numpy as np

with open(CONFIG_DIR / "seed_config.json") as f: seed_cfg = json.load(f)
with open(CONFIG_DIR / "lora_config.json") as f: lora_cfg = json.load(f)
with open(CONFIG_DIR / "training_config.json") as f: train_cfg = json.load(f)

SEED = seed_cfg["seed"]
random.seed(SEED); np.random.seed(SEED); torch.manual_seed(SEED)
torch.cuda.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)
os.environ["PYTHONHASHSEED"] = str(SEED)

# --- SMOKE TEST TOGGLES ---
# will Flip USE_FULL_DATASET to True once you have flash-attn server access and want
# the real, full-scale run instead of this verification pass.
USE_FULL_DATASET = False
SMOKE_TRAIN_SIZE = 300
SMOKE_VAL_SIZE = 60
SMOKE_EPOCHS = 2

EVAL_STRATEGY = "epoch"
SAVE_STRATEGY = "epoch"
PER_DEVICE_BATCH = 1
GRAD_ACCUM = train_cfg["gradient_accumulation_steps"] * train_cfg["train_batch_size"] // PER_DEVICE_BATCH
print(f"Effective batch size: {PER_DEVICE_BATCH} x {GRAD_ACCUM} = {PER_DEVICE_BATCH*GRAD_ACCUM}")
print("Mode:", "FULL DATASET" if USE_FULL_DATASET else f"SMOKE TEST ({SMOKE_TRAIN_SIZE} train / {SMOKE_VAL_SIZE} val rows, {SMOKE_EPOCHS} epochs)")

Effective batch size: 1 x 16 = 16
Mode: SMOKE TEST (300 train / 60 val rows, 2 epochs)

In [ ]:
#LOAD DATASET
#by mistake i re-run the cell thts why the error came
import pandas as pd

train_df_full = pd.read_csv(SPLIT_DIR / "train.csv")
val_df_full   = pd.read_csv(SPLIT_DIR / "validation.csv")
test_df       = pd.read_csv(SPLIT_DIR / "test.csv")

if USE_FULL_DATASET:
    train_df = train_df_full
    val_df = val_df_full
else:
    train_df = train_df_full.sample(n=SMOKE_TRAIN_SIZE, random_state=SEED).reset_index(drop=True)
    val_df = val_df_full.sample(n=SMOKE_VAL_SIZE, random_state=SEED).reset_index(drop=True)

print(f"Train: {len(train_df)}  Val: {len(val_df)}  Test: {len(test_df)}")

N_EVAL_SAMPLES = 20 if not USE_FULL_DATASET else 100
eval_df = test_df.sample(n=min(N_EVAL_SAMPLES, len(test_df)), random_state=SEED).reset_index(drop=True)
few_shot_examples = train_df_full.sample(n=3, random_state=SEED)[["instruction", "output"]].to_dict("records")
print(f"Eval samples: {len(eval_df)}")

NameError: name 'SPLIT_DIR' is not defined

In [ ]:
from unsloth import FastLanguageModel

MODEL_NAME = "unsloth/Phi-4-mini-instruct-unsloth-bnb-4bit"
MAX_SEQ_LENGTH = train_cfg["max_seq_length"]

def load_base_model():
    m, tok = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=True,
    )
    return m, tok

model, tokenizer = load_base_model()
print("Model loaded.")

This model config has set a `rope_parameters['original_max_position_embeddings']` field, to be used together with `max_position_embeddings` to determine a scaling factor. Please set the `factor` field of `rope_parameters`with this ratio instead -- we recommend the use of this field over `original_max_position_embeddings`, as it is compatible with most model architectures.

==((====))==  Unsloth 2026.7.5: Fast Phi3 patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/194 [00:00<?, ?it/s]

Model loaded.

In [ ]:
#Few-shot examples
#-----------------

@torch.no_grad()
def generate_shloka(model, instruction_prompt, few_shot=None, max_new_tokens=100):
    messages = []
    if few_shot:
        for ex in few_shot:
            messages.append({"role": "user", "content": ex["instruction"]})
            messages.append({"role": "assistant", "content": ex["output"]})
    messages.append({"role": "user", "content": instruction_prompt})

    input_ids = tokenizer.apply_chat_template(
        messages, add_generation_prompt=True, return_tensors="pt"
    ).to(model.device)

    out = model.generate(
        input_ids, max_new_tokens=max_new_tokens, do_sample=False,
        pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
    )
    return tokenizer.decode(out[0][input_ids.shape[1]:], skip_special_tokens=True).strip()

def generate_for_dataframe(model, df, few_shot=None, max_new_tokens=100):
    results = []
    for i, row in enumerate(df.itertuples(), 1):
        results.append(generate_shloka(model, row.instruction, few_shot, max_new_tokens))
        if i % 10 == 0:
            print(f"  generated {i}/{len(df)}")
    out = df.copy()
    out["generated"] = results
    return out

In [ ]:
FastLanguageModel.for_inference(model)

print("Baseline ZERO-SHOT...")
baseline_zero_df = generate_for_dataframe(model, eval_df, few_shot=None)
baseline_zero_df.to_csv(OUTPUT_DIR / "baseline_zero_shot.csv", index=False)

print("Baseline 3-SHOT...")
baseline_three_df = generate_for_dataframe(model, eval_df, few_shot=few_shot_examples)
baseline_three_df.to_csv(OUTPUT_DIR / "baseline_three_shot.csv", index=False)
print("Saved.")

Baseline ZERO-SHOT...

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 10/20

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 20/20

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Baseline 3-SHOT...

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 10/20

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 20/20
Saved.

In [ ]:
import re
from skrutable.meter_identification import MeterIdentifier
from sentence_transformers import SentenceTransformer

VALID_ANUSTUBH_PATTERN = re.compile(
    r'^anuṣṭubh \(\d,\d: (?!asamīcīna).+?[;,] \d,\d: (?!asamīcīna).+?\)$'
)
meter_checker = MeterIdentifier()
similarity_model = SentenceTransformer("sanganaka/bge-m3-sanskritFT")

def check_one_verse(verse_text):
    try:
        meter_info = meter_checker.identify_meter(verse_text, from_scheme="DEV")
    except Exception:
        return 0, False
    syllable_count = len(meter_info.syllable_weights.replace("\n", ""))
    is_full_anustubh = bool(VALID_ANUSTUBH_PATTERN.match(meter_info.meter_label))
    return syllable_count, is_full_anustubh

def evaluate_generations(df, label=""):
    syllable_counts, full_flags = [], []
    for verse in df["generated"]:
        n_syl, is_full = check_one_verse(verse)
        syllable_counts.append(n_syl)
        full_flags.append(is_full)

    n = len(df)
    full_pct = 100 * sum(full_flags) / n
    half_pct = max(100 * sum(c == 32 for c in syllable_counts) / n, full_pct)

    meaning_embs = similarity_model.encode(df["input"].tolist(), convert_to_tensor=True)
    gen_embs = similarity_model.encode(df["generated"].tolist(), convert_to_tensor=True)
    cosine_scores = similarity_model.similarity_pairwise(meaning_embs, gen_embs)
    similarity_pct = ((torch.pi - cosine_scores.arccos()) * 100 / torch.pi).mean().item()

    return {"run": label, "n_samples": n, "full_anustubh_pct": full_pct,
            "half_anustubh_pct": half_pct, "semantic_similarity_pct": similarity_pct}

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/199 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/45.1k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/736 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/1.36k [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/297 [00:00<?, ?B/s]

In [ ]:
baseline_zero_result  = evaluate_generations(baseline_zero_df,  "baseline_zero_shot")
baseline_three_result = evaluate_generations(baseline_three_df, "baseline_three_shot")
pd.DataFrame([baseline_zero_result, baseline_three_result])

,run,n_samples,full_anustubh_pct,half_anustubh_pct,semantic_similarity_pct
0,baseline_zero_shot,20,0.0,0.0,74.591202
1,baseline_three_shot,20,35.0,35.0,69.858803

In [ ]:
del model
torch.cuda.empty_cache()

model, tokenizer = load_base_model()

model = FastLanguageModel.get_peft_model(
    model,
    r=lora_cfg["r"],
    lora_alpha=lora_cfg["lora_alpha"],
    lora_dropout=lora_cfg["lora_dropout"],
    bias=lora_cfg["bias"],
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    use_gradient_checkpointing="unsloth",
    random_state=SEED,
)
model.print_trainable_parameters()

==((====))==  Unsloth 2026.7.5: Fast Phi3 patching. Transformers: 5.5.0.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.11.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.6.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.35. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Loading weights:   0%|          | 0/194 [00:00<?, ?it/s]

Unsloth: Explicit target_modules are constrained by the finetune_(vision|language|attention|mlp) filters; adapters attach only where both select.

Unsloth: Dropout = 0 is supported for fast patching. You are using dropout = 0.05.
Unsloth will patch all other layers, except LoRA matrices, causing a performance hit.

trainable params: 4,456,448 || all params: 3,840,478,208 || trainable%: 0.1160

In [ ]:
from datasets import Dataset

def tokenize_row(row):
    prompt_msgs = [{"role": "user", "content": row["instruction"]}]
    full_msgs = prompt_msgs + [{"role": "assistant", "content": row["output"]}]
    prompt_ids = tokenizer.apply_chat_template(prompt_msgs, add_generation_prompt=True)
    full_ids = tokenizer.apply_chat_template(full_msgs, add_generation_prompt=False)[:MAX_SEQ_LENGTH]
    labels = list(full_ids)
    for i in range(min(len(prompt_ids), len(full_ids))):
        labels[i] = -100
    return {"input_ids": full_ids, "attention_mask": [1]*len(full_ids), "labels": labels}

train_dataset = Dataset.from_pandas(train_df[["instruction","output"]], preserve_index=False).map(
    tokenize_row, remove_columns=["instruction","output"])
val_dataset = Dataset.from_pandas(val_df[["instruction","output"]], preserve_index=False).map(
    tokenize_row, remove_columns=["instruction","output"])

def collate_fn(batch):
    max_len = max(len(x["input_ids"]) for x in batch)
    pad_id = tokenizer.pad_token_id or tokenizer.eos_token_id
    input_ids, attention_mask, labels = [], [], []
    for x in batch:
        pad_len = max_len - len(x["input_ids"])
        input_ids.append(x["input_ids"] + [pad_id]*pad_len)
        attention_mask.append(x["attention_mask"] + [0]*pad_len)
        labels.append(x["labels"] + [-100]*pad_len)
    return {"input_ids": torch.tensor(input_ids),
            "attention_mask": torch.tensor(attention_mask),
            "labels": torch.tensor(labels)}

print(f"Tokenized. Train: {len(train_dataset)}  Val: {len(val_dataset)}")

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

Map:   0%|          | 0/60 [00:00<?, ? examples/s]

Tokenized. Train: 300  Val: 60

In [ ]:
from transformers import TrainingArguments, Trainer

FastLanguageModel.for_training(model)
CHECKPOINT_DIR = MODEL_DIR / "phi4_lora_checkpoints_smoketest"

training_args = TrainingArguments(
    output_dir=str(CHECKPOINT_DIR),
    num_train_epochs=SMOKE_EPOCHS if not USE_FULL_DATASET else train_cfg["num_train_epochs"],
    per_device_train_batch_size=PER_DEVICE_BATCH,
    per_device_eval_batch_size=PER_DEVICE_BATCH,
    gradient_accumulation_steps=GRAD_ACCUM,
    learning_rate=train_cfg["learning_rate"],
    weight_decay=train_cfg["weight_decay"],
    warmup_ratio=train_cfg["warmup_ratio"],
    lr_scheduler_type=train_cfg["lr_scheduler_type"],
    logging_steps=5,
    eval_strategy=EVAL_STRATEGY,
    save_strategy=SAVE_STRATEGY,
    load_best_model_at_end=train_cfg["load_best_model_at_end"],
    metric_for_best_model=train_cfg["metric_for_best_model"],
    greater_is_better=train_cfg["greater_is_better"],
    save_total_limit=2,
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    report_to="none",
    seed=SEED,
)

trainer = Trainer(
    model=model, args=training_args,
    train_dataset=train_dataset, eval_dataset=val_dataset,
    data_collator=collate_fn,
)
trainer.train()

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 300 | Num Epochs = 2 | Total steps = 38
O^O/ \_/ \    Batch size per device = 1 | Gradient accumulation steps = 16
\        /    Data Parallel GPUs = 1 | Total batch size (1 x 16 x 1) = 16
 "-____-"     Trainable parameters = 4,456,448 of 3,840,478,208 (0.12% trained)

TrainOutput(global_step=38, training_loss=3.1532303659539473, metrics={'train_runtime': 419.66, 'train_samples_per_second': 1.43, 'train_steps_per_second': 0.091, 'total_flos': 2919319619788800.0, 'train_loss': 3.1532303659539473, 'epoch': 2.0})

In [ ]:
#SAVING THE TRAINING
#-------------------

SUFFIX = "_smoketest" if not USE_FULL_DATASET else "_final"
FINAL_ADAPTER_DIR = MODEL_DIR / f"phi4_lora{SUFFIX}"
trainer.save_model(str(FINAL_ADAPTER_DIR))
tokenizer.save_pretrained(str(FINAL_ADAPTER_DIR))
print("Saved to", FINAL_ADAPTER_DIR)

Unsloth: Restored added_tokens_decoder metadata in /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/models/phi4_lora_smoketest/tokenizer_config.json.

Saved to /content/drive/MyDrive/Sanskrit_Phi4_Finetuning/models/phi4_lora_smoketest

In [ ]:
FastLanguageModel.for_inference(model)

print("Trained ZERO-SHOT...")
trained_zero_df = generate_for_dataframe(model, eval_df, few_shot=None)
trained_zero_df.to_csv(OUTPUT_DIR / f"trained_zero_shot{SUFFIX}.csv", index=False)

print("Trained 3-SHOT...")
trained_three_df = generate_for_dataframe(model, eval_df, few_shot=few_shot_examples)
trained_three_df.to_csv(OUTPUT_DIR / f"trained_three_shot{SUFFIX}.csv", index=False)
print("Saved.")

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Trained ZERO-SHOT...

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 10/20

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 20/20
Trained 3-SHOT...

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 10/20

Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
Both `max_new_tokens` (=100) and `max_length`(=131072) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

  generated 20/20
Saved.

In [ ]:
trained_zero_result  = evaluate_generations(trained_zero_df,  "trained_zero_shot")
trained_three_result = evaluate_generations(trained_three_df, "trained_three_shot")

comparison_df = pd.DataFrame([
    baseline_zero_result, baseline_three_result,
    trained_zero_result, trained_three_result,
])
comparison_df.to_csv(PROJECT_DIR / "outputs" / f"comparison{SUFFIX}.csv", index=False)
print(f"--- Mode: {'FULL' if USE_FULL_DATASET else 'SMOKE TEST'} ---")
print(comparison_df.to_string(index=False))

--- Mode: SMOKE TEST ---
                run  n_samples  full_anustubh_pct  half_anustubh_pct  semantic_similarity_pct
 baseline_zero_shot         20                0.0                0.0                74.591202
baseline_three_shot         20               35.0               35.0                69.858803
  trained_zero_shot         20               20.0               20.0                66.398331
 trained_three_shot         20               35.0               35.0                68.460800

In [ ]:
!pip freeze | grep -E -i "^(torch|transformers|peft|accelerate|datasets|bitsandbytes|unsloth|trl|sentence-transformers|skrutable)" > requirements.txt
!cp requirements.txt "{PROJECT_DIR}/requirements.txt"
print(open("requirements.txt").read())

accelerate==1.14.0
bitsandbytes==0.50.0
datasets==4.3.0
peft==0.19.1
sentence-transformers==5.6.0
skrutable==2.9.2
torch==2.11.0+cu128
torchao==0.17.0
torchaudio==2.11.0+cu128
torchcodec==0.11.0+cu128
torchdata==0.11.0
torchsummary==1.5.1
torchtune==0.6.1
torchvision==0.26.0+cu128
transformers==5.5.0
trl==0.24.0
unsloth==2026.7.5
unsloth_zoo==2026.7.6

In [1]:
!ls

sample_data

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!find "/content/drive/MyDrive" -maxdepth 2

/content/drive/MyDrive
/content/drive/MyDrive/Colab Notebooks
/content/drive/MyDrive/Colab Notebooks/baseline_predictions.json
/content/drive/MyDrive/Colab Notebooks/checkpoint_2500.zip
/content/drive/MyDrive/Colab Notebooks/.ipynb_checkpoints
/content/drive/MyDrive/Colab Notebooks/Untitled0.ipynb
/content/drive/MyDrive/Colab Notebooks/LLM_finetuning_final.ipynb
/content/drive/MyDrive/Colab Notebooks/Final_assignment.ipynb
/content/drive/MyDrive/Colab Notebooks/LLM_finetuning.ipynb
/content/drive/MyDrive/Colab Notebooks/ASSIGNMENT_final.ipynb
/content/drive/MyDrive/Colab Notebooks/Assignment.ipynb
/content/drive/MyDrive/Colab Notebooks/phi4_anustubh_finetuning_v2.ipynb
/content/drive/MyDrive/Colab Notebooks/Untitled
/content/drive/MyDrive/Colab Notebooks/phi4_anustubh_finetuning_v3_unsloth.ipynb
/content/drive/MyDrive/Colab Notebooks/phi4_anustubh_finetuning_v4_instructor_stack.ipynb
/content/drive/MyDrive/Colab Notebooks/phi4_anustubh_smoketest_v5.ipynb
/content/drive/MyDrive/Colab Notebooks/Copy of Anustubh Experiment.ipynb
/content/drive/MyDrive/Colab Notebooks/Anustubh Experiment.ipynb
/content/drive/MyDrive/.ipynb_checkpoints
/content/drive/MyDrive/colab files
/content/drive/MyDrive/colab files/baseline_predictions.json
/content/drive/MyDrive/colab files/checkpoint_2500.zip
/content/drive/MyDrive/LLM_Finetuning_Assignment
/content/drive/MyDrive/LLM_Finetuning_Assignment/dataset
/content/drive/MyDrive/LLM_Finetuning_Assignment/checkpoints
/content/drive/MyDrive/LLM_Finetuning_Assignment/baseline_predictions
/content/drive/MyDrive/LLM_Finetuning_Assignment/finetuned_predictions
/content/drive/MyDrive/LLM_Finetuning_Assignment/evaluation
/content/drive/MyDrive/LLM_Finetuning_Assignment/logs
/content/drive/MyDrive/LLM_Finetuning_Assignment/final_model
/content/drive/MyDrive/LLM_Finetuning_Assignment/predictions
/content/drive/MyDrive/LLM_Finetuning_Assignment/dataset_splits
/content/drive/MyDrive/Artifacts (1).zip
/content/drive/MyDrive/Artifacts.zip
/content/drive/MyDrive/Artifacts
/content/drive/MyDrive/Artifacts/logs
/content/drive/MyDrive/Artifacts/evaluation
/content/drive/MyDrive/Artifacts/checkpoints
/content/drive/MyDrive/Artifacts/final_model
/content/drive/MyDrive/Artifacts/dataset_splits
/content/drive/MyDrive/Artifacts/finetuned_predictions
/content/drive/MyDrive/Anustubh Experiment.zip
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/dataset
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/evaluation
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/outputs
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/models
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/logs
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/notebooks
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/configs
/content/drive/MyDrive/Sanskrit_Phi4_Finetuning/requirements.txt
/content/drive/MyDrive/stableenv.yml
/content/drive/MyDrive/Copy of Anustubh Experiment.ipynb